[Service]
PrivateDevices=yes
PrivateIPC=yes

ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectKernelLogs=yes
ProtectControlGroups=yes
ProtectClock=yes
ProtectHostname=yes
ProtectProc=invisible

CapabilityBoundingSet=
AmbientCapabilities=

RestrictSUIDSGID=yes
RestrictRealtime=yes
RestrictNamespaces=yes
LockPersonality=yes

SystemCallArchitectures=native
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK

MemoryDenyWriteExecute=yes
InaccessiblePaths=/dev/shm

SystemCallFilter=~@mount @raw-io @reboot @swap @obsolete memfd_create
SystemCallErrorNumber=EPERM

LimitNOFILE=65536
TasksMax=256

RemoveIPC=yes
