[Service]
# DynamicUser=yes enforces this already
NoNewPrivileges=yes
# DynamicUser=yes enforces this already
PrivateTmp=disconnected
# DynamicUser=yes enforces this already
ProtectSystem=strict
# DynamicUser=yes enforces this already
ProtectHome=read-only
# DynamicUser=yes enforces this already
RestrictSUIDSGID=yes
# DynamicUser=yes enforces this already
RemoveIPC=yes

PrivateDevices=yes
PrivateIPC=yes

ProtectHome=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectKernelLogs=yes
ProtectControlGroups=yes
ProtectClock=yes
ProtectHostname=yes
ProtectProc=invisible

CapabilityBoundingSet=
AmbientCapabilities=

RestrictRealtime=yes
RestrictNamespaces=yes
LockPersonality=yes

SystemCallArchitectures=native
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK

MemoryDenyWriteExecute=yes
InaccessiblePaths=/dev/shm

SystemCallFilter=~@mount @raw-io @reboot @swap @obsolete memfd_create
SystemCallErrorNumber=EPERM

LimitNOFILE=65536
TasksMax=256
